#!/usr/bin/env node

/**
 * Interactive Environment Setup Wizard
 * 
 * Kullanıcıya environment variable'ları ayarlaması için interaktif rehberlik eder.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const crypto = require('crypto');

const ENV_FILE = path.join(__dirname, '../.env.local');
const ENV_EXAMPLE = path.join(__dirname, '../.env.example');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// ANSI colors
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  bold: '\x1b[1m'
};

function log(message, color = colors.reset) {
  console.log(color + message + colors.reset);
}

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setupWizard() {
  log('\n🚀 YatayApp Environment Setup Wizard\n', colors.bold + colors.cyan);
  
  const envVars = {};

  // Check if .env.local exists
  if (fs.existsSync(ENV_FILE)) {
    log('⚠️  .env.local dosyası zaten mevcut.', colors.yellow);
    const overwrite = await question('   Üzerine yazmak ister misin? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      log('\n❌ Kurulum iptal edildi. Mevcut dosya korundu.\n', colors.red);
      rl.close();
      return;
    }
    
    // Backup existing file
    const backupFile = ENV_FILE + '.backup.' + Date.now();
    fs.copyFileSync(ENV_FILE, backupFile);
    log(`   ✅ Mevcut dosya yedeklendi: ${path.basename(backupFile)}\n`, colors.green);
  }

  log('📝 Gerekli bilgileri sırayla girelim:\n', colors.bold);

  // 1. Supabase URL
  log('1️⃣  Supabase Project URL', colors.cyan);
  log('   Nasıl bulunur: https://app.supabase.com → Project → Settings → API', colors.blue);
  const supabaseUrl = await question('   URL: ');
  if (!supabaseUrl || !supabaseUrl.includes('supabase.co')) {
    log('   ⚠️  Geçersiz URL, boş bırakıldı', colors.yellow);
  } else {
    envVars.NEXT_PUBLIC_SUPABASE_URL = supabaseUrl;
    log('   ✅ Kaydedildi\n', colors.green);
  }

  // 2. Supabase Anon Key
  log('2️⃣  Supabase Anon Key', colors.cyan);
  log('   Aynı sayfadan "anon" / "public" key\'i kopyala', colors.blue);
  const anonKey = await question('   Key: ');
  if (!anonKey || anonKey.length < 20) {
    log('   ⚠️  Geçersiz key, boş bırakıldı', colors.yellow);
  } else {
    envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY = anonKey;
    log('   ✅ Kaydedildi\n', colors.green);
  }

  // 3. Demo Mode
  log('3️⃣  Demo Mode (Opsiyonel)', colors.cyan);
  log('   Demo butonlarını aktif etmek ister misin?', colors.blue);
  const demoMode = await question('   Aktif et? (Y/n): ');
  if (demoMode.toLowerCase() !== 'n') {
    envVars.NEXT_PUBLIC_DEMO_MODE = 'true';
    
    // Auto-generate demo setup token
    const demoToken = crypto.randomBytes(32).toString('hex');
    envVars.DEMO_SETUP_TOKEN = demoToken;
    
    log('   ✅ Demo mode aktif edildi', colors.green);
    log('   ✅ Güvenli token otomatik oluşturuldu\n', colors.green);
  } else {
    envVars.NEXT_PUBLIC_DEMO_MODE = 'false';
    log('   ℹ️  Demo mode kapalı\n', colors.blue);
  }

  // 4. Service Role Key (for E2E)
  log('4️⃣  Supabase Service Role Key (Opsiyonel - E2E testler için)', colors.cyan);
  log('   ⚠️  Bu key admin yetkilerine sahiptir!', colors.yellow);
  log('   Nasıl bulunur: Supabase Dashboard → Settings → API → "service_role"', colors.blue);
  const wantServiceRole = await question('   Eklemek ister misin? (y/N): ');
  if (wantServiceRole.toLowerCase() === 'y') {
    const serviceRole = await question('   Service Role Key: ');
    if (serviceRole && serviceRole.length > 20) {
      envVars.SUPABASE_SERVICE_ROLE_KEY = serviceRole;
      log('   ✅ Kaydedildi (E2E testler çalışacak)\n', colors.green);
    } else {
      log('   ⚠️  Geçersiz key, atlandı\n', colors.yellow);
    }
  } else {
    log('   ℹ️  Atlandı (E2E testler skip edilecek)\n', colors.blue);
  }

  // 5. Sentry (Optional)
  log('5️⃣  Sentry DSN (Opsiyonel - Error tracking)', colors.cyan);
  const wantSentry = await question('   Eklemek ister misin? (y/N): ');
  if (wantSentry.toLowerCase() === 'y') {
    const sentryDsn = await question('   Sentry DSN: ');
    if (sentryDsn && sentryDsn.startsWith('https://')) {
      envVars.NEXT_PUBLIC_SENTRY_DSN = sentryDsn;
      log('   ✅ Kaydedildi\n', colors.green);
    } else {
      log('   ⚠️  Geçersiz DSN, atlandı\n', colors.yellow);
    }
  } else {
    log('   ℹ️  Atlandı\n', colors.blue);
  }

  // Write to .env.local
  log('💾 .env.local dosyası oluşturuluyor...\n', colors.bold);
  
  let envContent = '# Auto-generated by setup-wizard.cjs\n';
  envContent += '# ' + new Date().toISOString() + '\n\n';
  envContent += '# Supabase Configuration\n';
  envContent += `NEXT_PUBLIC_SUPABASE_URL=${envVars.NEXT_PUBLIC_SUPABASE_URL || ''}\n`;
  envContent += `NEXT_PUBLIC_SUPABASE_ANON_KEY=${envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''}\n\n`;
  
  if (envVars.NEXT_PUBLIC_DEMO_MODE) {
    envContent += '# Demo Mode\n';
    envContent += `NEXT_PUBLIC_DEMO_MODE=${envVars.NEXT_PUBLIC_DEMO_MODE}\n`;
    if (envVars.DEMO_SETUP_TOKEN) {
      envContent += `DEMO_SETUP_TOKEN=${envVars.DEMO_SETUP_TOKEN}\n\n`;
    }
  }
  
  if (envVars.SUPABASE_SERVICE_ROLE_KEY) {
    envContent += '# Admin Operations (E2E Tests)\n';
    envContent += `SUPABASE_SERVICE_ROLE_KEY=${envVars.SUPABASE_SERVICE_ROLE_KEY}\n\n`;
  }
  
  if (envVars.NEXT_PUBLIC_SENTRY_DSN) {
    envContent += '# Error Tracking\n';
    envContent += `NEXT_PUBLIC_SENTRY_DSN=${envVars.NEXT_PUBLIC_SENTRY_DSN}\n\n`;
  }

  fs.writeFileSync(ENV_FILE, envContent);
  
  log('✅ .env.local dosyası oluşturuldu!\n', colors.green + colors.bold);
  
  // Summary
  log('📊 Özet:', colors.bold);
  log('   • Supabase URL: ' + (envVars.NEXT_PUBLIC_SUPABASE_URL ? '✅' : '❌'), envVars.NEXT_PUBLIC_SUPABASE_URL ? colors.green : colors.red);
  log('   • Supabase Anon Key: ' + (envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY ? '✅' : '❌'), envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY ? colors.green : colors.red);
  log('   • Demo Mode: ' + (envVars.NEXT_PUBLIC_DEMO_MODE === 'true' ? '✅ Aktif' : '❌ Kapalı'), envVars.NEXT_PUBLIC_DEMO_MODE === 'true' ? colors.green : colors.yellow);
  log('   • Service Role Key: ' + (envVars.SUPABASE_SERVICE_ROLE_KEY ? '✅ Var' : '❌ Yok'), envVars.SUPABASE_SERVICE_ROLE_KEY ? colors.green : colors.yellow);
  log('   • Sentry: ' + (envVars.NEXT_PUBLIC_SENTRY_DSN ? '✅ Var' : '❌ Yok'), envVars.NEXT_PUBLIC_SENTRY_DSN ? colors.green : colors.yellow);
  
  log('\n🎉 Kurulum tamamlandı!', colors.green + colors.bold);
  log('\n📝 Sonraki adımlar:', colors.cyan);
  log('   1. npm run check:env  # Kontrol et');
  log('   2. npm run dev        # Geliştirme sunucusunu başlat\n');
  
  rl.close();
}

// Run wizard
setupWizard().catch(err => {
  log('\n❌ Hata: ' + err.message, colors.red);
  rl.close();
  process.exit(1);
});
